### ISSUE TITLE
No shadows in Just Cause

### ISSUE THREAD

**Issue by mtmkls** [iXit/Mesa-3D#261]
Shadows are not drawn at all.

**Comment by axeldavy** [comment]
Is there shadows when using wined3d ?

**Comment by mtmkls** [comment]
With wined3d the game seems to render perfectly, it's just painfully slow.

After some more observation I noticed that there are shadows, but they are really faint. Their strength depends on the viewing angle (strongest shadow when viewing from the direction of the sun), and their location (shadows on objects are much stronger than shadows on terrain, shadows are stronger on the side of the cars than on their roofs).

**Comment by axeldavy** [comment]
would you have a comparison screenshot ?

**Comment by mtmkls** [comment]
nine
![nine](https://cloud.githubusercontent.com/assets/957339/21658473/1a739758-d2c7-11e6-890d-8228c7e4875e.jpg)
wined3d
![wined3d](https://cloud.githubusercontent.com/assets/957339/21658474/1a764f02-d2c7-11e6-89de-313816be1041.jpg)

**Comment by axeldavy** [comment]
Interesting.

The best to fix this issue would be have a trace showing the bug.
It's a bit hard to use apitrace on wine.
From memory, if using Steam, one way is to start Steam, then replace the d3d9.dll in windows/system32/ directory with the one of apitrace and set d3d9.dll in winecfg to native then integrated (Or perhaps apitrace dll just needs to be in the game directory). It may be a bit trickier to take a trace with nine rather than wined3d active (because nine uses "d3d9-nine.dll"). I don't remember what trick I used in the past to get trace, perhaps disable nine, but rename d3d9-nine.dll to d3d9.dll.

If you managed to get everything working properly (game loads apitrace d3d9.dll which then load the default d3d9.dll either wined3d or nine), a trace should appear in the game directory.

If not using Steam, it should be easier. A way to get it working is described here: https://github.com/apitrace/apitrace/wiki/WINE
Another way is to put apitrace d3d9.dll in the game directory and use winecfg to set d3d9.dll to native then integrated.

**Comment by mtmkls** [comment]
Now that the patch landed in Mesa master I verified that the shadows are now visible. I still get #260 though.
