### ISSUE TITLE
GRID crashes before reaching the menu

### ISSUE THREAD

**Issue by mtmkls** [iXit/Mesa-3D#285]
Unhandled exception: assertion failed in 32-bit code (0xf77e8af9).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:f77e8af9 ESP:0544dd70 EBP:0544dd80 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:00000000 EBX:00000002 ECX:0544dd80 EDX:00000000
 ESI:00000008 EDI:00000000
Stack dump:
0x0544dd70:  0544dd80 00000000 0544dd80 f741adc0
0x0544dd80:  00000000 00000000 00000008 00000000
0x0544dd90:  00000000 00100000 f74d2764 f75a2000
0x0544dda0:  44900010 00021000 f7407365 f745cba2
0x0544ddb0:  00000000 00100000 00000000 00004022
0x0544ddc0:  ffffffff 00000000 f7407365 f745eb3a
Backtrace:
=>0 0xf77e8af9 __kernel_vsyscall+0x9() in [vdso].so (0x0544dd80)
  1 0xf741adc0 gsignal+0xaf() in libc.so.6 (0x0544dd80)
  2 0xf741c287 abort+0x156() in libc.so.6 (0x411637c8)
  3 0xf7413a17 in libc.so.6 (+0x24a16) (0x411637c8)
  4 0xf7413a9b __assert_fail+0x3a() in libc.so.6 (0x411637c8)
  5 0x45596a03 si_draw_vbo+0xd82() in d3dadapter9.so.1 (0x411637c8)
  6 0x45301e6e blitter_draw+0x22d() in d3dadapter9.so.1 (0x00000000)
  7 0x4530264e do_blits+0x34d() in d3dadapter9.so.1 (0x0544e4f0)
  8 0x45305c9c util_blitter_blit_generic+0xa2b() in d3dadapter9.so.1 (0x00000000)
  9 0x45306649 util_blitter_blit+0xc8() in d3dadapter9.so.1 (0x7bb3ee78)
  10 0x45556bc0 si_blit+0x13f() in d3dadapter9.so.1 (0x0544e4e8)
  11 0x45455881 NineSwapChain9_Present+0x290() in d3dadapter9.so.1 (0x0544e598)
  12 0x453c41aa NineDevice9_Present+0x99() in d3dadapter9.so.1 (0x0544e5f8)
  13 0x45414a7b LockDevice9_Present+0x5a() in d3dadapter9.so.1 (0x0544e658)
  14 0x7e95288c in d3d9 (+0x1288b) (0x0544e698)
  15 0x0175a068 in gameoverlayrenderer (+0x6a067) (0x0544e708)
  16 0x00a9de2e in grid (+0x69de2d) (0x0544e9c4)
  17 0x0087260a in grid (+0x472609) (0x0040ef50)
  18 0x660f57e8 (0x08244c8b)
  19 0x00000908 (0x23044000)
0xf77e8af9 __kernel_vsyscall+0x9 in [vdso].so: popl	%ebp

This is the first GRID that is no longer in the Steam store (appid 12750).

**Comment by mtmkls** [comment]
For wined3d see https://bugs.freedesktop.org/show_bug.cgi?id=101928

**Comment by axeldavy** [comment]
Does this crash at about the same time that for wine opengl ?

I guess the game does set some invalid settings, and somehow it is badly handled.
It would be great if you could generate a log (NINE_DEBUG=all   does only work with mesa built with --enable-debug)

**Comment by mtmkls** [comment]
Well, there is a slight difference between "crashes before reaching the menu" and "crashes mid-race".

Here's a full log:
[nine_grid.txt.gz](https://github.com/iXit/Mesa-3D/files/1223131/nine_grid.txt.gz)

**Comment by leipero** [comment]
Just to confirm this bug, it might be connected with crash in Warframe (also on nine only).

**Comment by axeldavy** [comment]
I don't think it is connected to the Warframe issue according to the log.

mtmkls indicates an assert failure. Could a new log with the assert failure be made with mesa git ? The code changes often, and the assert may have changed location.

**Comment by leipero** [comment]
Here's another log for you, maybe it isn't, should I create Warframe log also and open a thread (or add it toe xisting one if there is any)?

https://drive.google.com/open?id=0B_j0gO_cc4rXYWxpU1llX1ZKM0U

**Comment by axeldavy** [comment]
is it crashing with this log ? I don't see any error

**Comment by leipero** [comment]
Yes, I've used NINE_DEBUG=all GALLIUM_LOG_FILE=location to save the log instead of redirecting terminal output, maybe because of that?

**Comment by axeldavy** [comment]
Yes, please redirect the terminal output please.

**Comment by leipero** [comment]
I'm getting empty file for some reason when doing that... (I must be doing something wrong), will do tomorow and post log.

**Comment by leipero** [comment]
Here is another log, hopefully this will be helpful:

https://drive.google.com/open?id=0B_j0gO_cc4rXa2lLNFNyYWVUQ3c

**Comment by axeldavy** [comment]
Apparently it's an out of memory here. How much ram do you have, and how many does your card have ?

**Comment by leipero** [comment]
It's 1024M VRAM and 8GB RAM, that is also a problem in WINE D3D, GRID shouldn't use anywhere near that. There was a workaround according to the winehq reports for setting vram amount to prevent crash but that doesn't work anymore and it's only aplicable to wine D3D anyway.

The crash happens when profile is getting loaded, with wine D3D it loads just fine (it does crash during the race, or on the race start with out of memory error in terminal, depending on wine version).

**Comment by axeldavy** [comment]
IT's 32 bits, right ?

**Comment by leipero** [comment]
Yeah ofc., debug is from 32-bit prefix I use, but I also tested it in clean prefixes before. Will have to do extensive test, it's GOG version of the game.

**Comment by siro20** [comment]
Got a nine debug log for "GRID crashes before reaching the menu"
```
nine:0x0548fb40:device9:CreateOffscreenPlainSurface: This=0x3b6bfdd8 Width=1024 Height=1024 Format=D3DFMT_A8R8G8B8(0x15) Pool=2 ppSurface=0x548e644 pSharedHandle=(nil)
nine:0x0548fb40:create_zs_or_rt_surface This=0x3b6bfdd8 type=2 Pool=SYSTEMMEM Width=1024 Height=1024 Format=D3DFMT_A8R8G8B8 MS=0 Quality=0 Discard_or_Lockable=1 ppSurface=0x548e644 pSharedHandle=(nil)
nine:0x0548fb40:surface9:ctor: This=0x2128eb68 pDevice=0x3b6bfdd8 pResource=(nil) Level=0 Layer=0 pDesc=0x548e480
nine:0x0548fb40:surface9:dtor: This=0x2128eb68
nine:0x0548fb40:resource9:dtor: This=0x2128eb68
nine:0x0548fb40:device9:CreateOffscreenPlainSurface: Failed to create surface.
nine:0x0548fb40:device9:GetRenderTargetData: This=0x3b6bfdd8 pRenderTarget=0x39aeea08 pDestSurface=(nil)
nine:0x0548fb40:device9:GetRenderTargetData: User assertion failed: `pRenderTarget && pDestSurface'
wine: Unhandled page fault on read access to 0x00000000 at address 0xba9a10 (thread 00ab), starting debugger...

```

**Comment by siro20** [comment]
On 32bit we should try to minimize memory usage, and only advertise   This->available_texture_mem = INT_MAX; instead of 4GiB. It will lead to outofvideomemory earlier and may prevent overallocation.

**Comment by ManoaNosea** [comment]
I have tested (very recently, on nine 3.0 git feb 8 2018 version) race driver GRID: glad to report that the game here works PERFECTLY, there are a few differences in my configuration, first my version of GRID is from the hardcopy release, not from GOG, it is heavily modified with many many graphics mods, I use the EXE with the 4gb patch (so that game may see all 4 GB of virtual address space, instead of just 2GB) and I am using WOW64 configuration, also using nouveau not the nvidea drivers with 3GB of video memory not 1. but in previous versions of wine/nine I did experience GL_OUT_OF_MEMORY errors in GRID, I think in nine 3.0 they are fixed ?

**Comment by leipero** [comment]
@ManoaNosea I can't confirm your results (on r600, both wine 3.0 and 3.2), however I did found out what the problem is. It have nothing to do with nine state tracker, and everything to do with wine itself, it just so hapens that with nine state tracker crash happens more quickly (probably because of higher framerate).

Anyway, solution to this problem is simple (in wine 3.2), new prefix (I've used 32-bit) adding OpenAL32.dll (6.14.357.22 or 24) to the GRID folder, adding openal32 in winecfg and setting it as native. After that running "winetricks sound=disabled".

After that, game runs fine with both wine d3d and gallium nine, it actually works perfectly, ultra settings and 4xAA (probably 8xAA too) on 1080p.

Since sympthoms are the same for the bug reporter as i had it ("crashes before reaching the menu" in gallium nine and "crashes mid-race" in wine d3d), I think it's safe to assume it is the same problem, and it should be safe to close bug report, since it is a wine bug, not nine.

**Comment by axeldavy** [comment]
Ok, thanks for the testing.

**Comment by mtmkls** [comment]
Unfortunately I can't re-test this, because a few weeks ago I did a dist-upgrade, and since then nine hangs on startup of any game. I tried to recompile mesa and wine, but it didn't help.

**Comment by axeldavy** [comment]
You possibly hit this issue
https://bugs.freedesktop.org/show_bug.cgi?id=105442
https://bugs.llvm.org/show_bug.cgi?id=36704

**Comment by mtmkls** [comment]
Nope, see #310

**Comment by leipero** [comment]
You might have some distribution specific problems, or llvm problem (r600 doesn't use llvm so for me it doesn't matter). I'm on 4.15.8, Mesa 17.3.6, WINE 3.3, llvm 5.0.1, X.Org 1.19.6 (all Arch packages from official stable repositories) and I can still run the game without problem.

However, since WINE version 3.0 (or at least 3.2, I did not investigated), in GRID I get black screen with only "loading" and similar things showed, overriding d3dx9_41 resolves that (for GRID at least), you can try it that way (documented on winehq).

Btw. I'm using this method for nine:
https://aur.archlinux.org/packages/wine-nine/

**Comment by mtmkls** [comment]
Now that the hang and the system crash have been resolved, I could re-test this. Grid starts up, but runs out of memory while in the menu (radeon: mmap failed, errno: 12). With wined3d I can navigate the menu, start a race, and it crashes while loading the map (same errno).

**Comment by leipero** [comment]
Even with "winetricks sound=disabled"? Try to replicate with these settings:
https://appdb.winehq.org/objectManager.php?sClass=version&iId=28327

**Comment by mtmkls** [comment]
With sound=disabled it's much better: wined3d doesn't crash, nine crashes mid-race. With sound=pulse wined3d crashes mid-race, nine crashes while loading the menu.

**Comment by leipero** [comment]
That seems to suggest that you are having same bug as me, do extensive testing, on r600 for me nine doesn't experience any crashes after doing exactly as on winehq page above, however, there are some graphical glitches on some maps that should go on separate bug report, it may as well be related to this specific GPU I use (Juniper).
