### ISSUE TITLE
Battle.net Launcher Freeze on Launch

### ISSUE THREAD

**Issue by whompy** [iXit/Mesa-3D#299]
When Gallium Nine is enabled, the Battle.net launcher fails to open. I tried to debug with the following to received the attached output:

NINE_DEBUG=all WINEDEBUG=+d3dadapter9,+d3d9 wine Diablo\ III.exe &> ~/diablo_debug.out  
[](url)
I believe I have debug symbols (installed debug packages for mesa and lib32-mesa), but I can separately compile if that doesn't seem to be the case. I lost the scripts, so it'll take me a bit to get that worked out.
[diablo_debug.txt](https://github.com/iXit/Mesa-3D/files/1610440/diablo_debug.txt)

Any ideas?

**Comment by Altosk** [comment]
Try this go into winecfh and set blizzard launcher to not use nine but
Diablo to use it .you'll have to set up specific apps defaults

On Jan 7, 2018 5:55 PM, "Nick Tenney" <notifications@github.com> wrote:

When Gallium Nine is enabled, the Battle.net launcher fails to open. I
tried to debug with the following to received the attached output:

NINE_DEBUG=all WINEDEBUG=+d3dadapter9,+d3d9 wine Diablo\ III.exe &>
~/diablo_debug.out
<http://url>
I believe I have debug symbols (installed debug packages for mesa and
lib32-mesa), but I can separately compile if that doesn't seem to be the
case. I lost the scripts, so it'll take me a bit to get that worked out.
diablo_debug.txt
<https://github.com/iXit/Mesa-3D/files/1610440/diablo_debug.txt>

Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iXit/Mesa-3D/issues/299>, or mute the thread

**Comment by whompy** [comment]
How would one go about disabling one of the staging features for one application? I am not aware of a section to do app-specific workarounds for such things.

Thanks!

**Comment by Altosk** [comment]
It works for me

**Comment by Altosk** [comment]
Winecfh save staging per app

**Comment by whompy** [comment]
All I see for application specific settings are Windows versions.

**Comment by Altosk** [comment]
it saves all tab to the specific app so long as you are clicked on that app

**Comment by whompy** [comment]
Okay. Finally had a chance to test, and no change.

**Comment by whompy** [comment]
Bug 300 ended being a better and more generic version. Closing this one and watching it instead.
