### ISSUE TITLE
[ACR Outfit]Wrong Texture

### ISSUE THREAD

**Issue by berillions** [iXit/Mesa-3D#311]
Hi,

With Assassin's Creed : Revelations + Wine staging/nine 3.5, Ezio's outfit is completely black. Like if a texture is missing. Screenshots explains better than words : 

- ACR + Nine enabled (Wrong Texture) : 
https://reho.st/self/60be2a2ef16886cbcf5cb0e40d44d8082a72fec7.jpg

- ACR + Nine disabled : 
https://reho.st/self/e756531adfbd8e5288f9ec9ea42924588f57e7fa.jpg

SYSTEM : 
- Gentoo amd64
- AMD Rx 560 - 4Go
- Mesa git + LLVM 5.0.1
- Wine-any 3.5

**Comment by iiv3** [comment]
Can you provide an apitrace? There is ftp where you can upload it.

Can you check if it works OK with older Mesa versions (18.0/17.3/17.2). Keep the same LLVM and Wine.

If it works with Mesa-17.3, you might try reverting the commit mentioned here:
https://bugs.freedesktop.org/show_bug.cgi?id=105333

**Comment by berillions** [comment]
Even with Mesa 17.3.7 i have the same issue.

I downloaded apitrace binaries but i don't know how to use it correctly. I did that but it does not work : 
- export WINEDEBUG=+debugstr
- export WINEDLLOVERRIDES='Z:\home\jfonseca\projects\apitrace\build\mingw32\wrappers\d3d9.dll=n'
- wine /mnt/HDData/Download/apitrace-mingw/x86/bin/apitrace.exe trace -a d3d9 -v ACRSP.exe

I have these lines : 
> info: did not find Z:\mnt\HDData\Download\apitrace-mingw\x86\bin\wrappers\d3d9.dll
> info: found Z:\mnt\HDData\Download\apitrace-mingw\x86\bin\..\lib\wrappers\d3d9.dll
> inject -D Z:\mnt\HDData\Download\apitrace-mingw\x86\bin\..\lib\wrappers\d3d9.dll -- ACRSP.exe

And i don't have .trace file.

**Comment by iiv3** [comment]
Since Steam and UPlay interfere with the way games are started I like to use the following method:
1. Put the wrapper d3d9.dll in the game directory (working or the one with .exe files).
2. in `winecfg` set library override for `d3d9` to `native,built-in`
3. Run the game.
4. Remove the d3d9.dll wrapper, or it will continue to make new traces :)
5. Check if the trace plays correctly with `d3dretrace.exe`

**Comment by berillions** [comment]
Ok the `apitrace` worked and plays correctly with `d3dretrace`. In fact, it just a video no ?
How you can find where come from the issue with that, i don't understand.

I uploaded the file in my mediafire repository : 
http://www.mediafire.com/file/3jvb8uiohdkf4x9/ACR_NINEISSUE.tar.xz

PS : To be sure, i did the apitrace without Nine enabled, it was ok ?

PS2: The goal of gallium-nine is to have better performance than wined3d, right ?
So why i have early the same performance +/- 5FPS than wined3d with FarCry 3 ?
--> I ask here because i don't know if i must to create a new bug report.

**Comment by axeldavy** [comment]
Thanks you for the trace. It was ok without nine enabled, because it replays fine under nine. Sometimes it doesn't and the trace would have needed nine enabled.

Yes, gallium-nine should have better performance than wined3d in general. Is the FarCry 3 performance close to what you would expect on windows, or far ? If both are close to windows, then there is no issue. If performance is far for both, then some optimisations are missing. Is gpu usage high or low ?(launch game with GALLIUM_HUD=GPU-load ) Wined3d improved a lot these last few years too.

**Comment by berillions** [comment]
Hi Axel,

I open a new report bug for FarCry3.
And about `Assassin's Creed : Revelations` i add too that i have drop FPS when i move the character. 
I add this screenshot to show you the drop when i play : 
https://reho.st/self/09ff1040ee1b5ff2d26a14dab01065e9a93383d7.jpg

I have these drops when there a cinematics, cutscene or when there are a lot of people. I'm not yet in Constantinople but i'm sure that i will have more drop than in the prologue.
--> These drop issue exists with `wined3d` too.

**Comment by berillions** [comment]
No news about this issue ? ^_^

**Comment by axeldavy** [comment]
Hi, I haven't yet looked the trace into detail.

**Comment by berillions** [comment]
Axel, your commit will be integrated in the officiel git repo of Mesa ?

**Comment by axeldavy** [comment]
yes, soon.
