### ISSUE TITLE
[r600][radeonsi]Witcher-1: Graphical glitches

### ISSUE THREAD

**Issue by siro20** [iXit/Mesa-3D#312]
https://bugs.freedesktop.org/show_bug.cgi?id=99403

**Comment by iiv3** [comment]
I've made an PIXWin trace of a single frame (uploaded to the ftp, major bugs).
PIXWin seems to work fine with latest wine and I can execute specific draw calls, while showing the rendered result (at the wrong place in the window but... it works).

What I find really strange is that I can trace the whole frame without single glitch.
After some point however, going back to previous drawing command breaks everything - hundred of previously working draws start producing artifacts.

What I did was trigger a glitch then go back to the first draw that does not show it. That is EID_11014.
The first draw that "might" show artifacts is EID_11036 .

I'll investigate further.

(I'm using HD5670 , Redwood Evergreen chip, r600 driver).

**Comment by iiv3** [comment]
The cause for this bug seems to have already been investigated by wine developers.
The registry option mentioned in the original bugreport is introduced specifically for this case.

The relevant part starts here: https://bugs.winehq.org/show_bug.cgi?id=34052#c42

**Comment by axeldavy** [comment]
Reading the bug report, I was like 'ah yes this is this undefined behaviour'. Basically reading outside bounds for constants with indirect adressing should return 0.0.
I see two ways of fixing the issue. Either we explicitly check bounds (what wine does when the registry var is set) or having the hw do it for us by reading the constant buffer as texture and setting a border color as 0.
The first solution is easier to set up, but maybe a small performance hit. Clamping rsq and rcp didn't change performance in a noticeable way, and they happen more often than indirect adressing, so probably we should we safe. We just have to check though that code scheduler are not perturbed with the change.

**Comment by iiv3** [comment]
They do mention that this behavior is clearly defined in D3D, it is undefined in OpenGL.
So it might worth the trouble of finding out how does the real D3D work in this case.

There might be another way to "handle" this case.
What I see is that at first draw the operations succeed. This is because the first draw operations use few constants. Once we have a draw operation with more constants, these constant remain in the buffer and are read when the first draw operations are performed again.

So a simple hack might be to zero the memory buffer that we use to hold the constants. 

 IIRC we upload the whole constant buffer for every draw operation. So we won't have an extra GPU penalty. We might even be smart about the zeroing and not do it on the entire buffer.

This might not handle the case where the index is outside the [0..255] range. Do you have idea how the hardware handles this case?

**Comment by axeldavy** [comment]
Just to make sure. With the patches on our git master, does it work now ?

**Comment by iiv3** [comment]
Applying the last 5 commits to 18.0.0.rc5 (should be same as 18.0.0) and playing back witcher1 trace, I get this:
```
witcher1/witcher.trace: nine_shader.c:1019: tx_src_param: 
Assertion `param->rel->file == D3DSPR_ADDR && param->rel->mod == NINED3DSPSM_NONE' 
failed. 
```

**Comment by rox4d** [comment]
It works with your git master.

**Comment by axeldavy** [comment]
Could you retest with the new git master ? The fix is different (and check if there is a performance difference too)

**Comment by rox4d** [comment]
This variant does not work.

**Comment by iiv3** [comment]
This commit ["r600: fix constant buffer bounds"](https://cgit.freedesktop.org/mesa/mesa/commit/?id=ce027ac5c798b39582288e5d7d9973b3cdda591e) fixes the bug for r600/Evergreen hardware.

@siro20, can you investigate the issue on your Tahiti?
Does the current manual checks in iXit/Mesa-3D fix the bug on it.
Does the OpenGL Trine1EE trace (from [this bugreport](https://bugs.freedesktop.org/show_bug.cgi?id=91808#c8) ) show artifacts on the Tahiti too?

**Comment by siro20** [comment]
Tested on Mesa 18.0.5 and radeonsi and nouveau. The rendering corruption as seen in the screenshot has been fixed.
