### ISSUE TITLE
GTA San Andreas no fog on the horizon

### ISSUE THREAD

**Issue by 18woldemar** [iXit/Mesa-3D#315]
During the game GTA San Andreas, noticed the lack of fog on the horizon. It looks bad because of that. Please fix this.
Operation System: Kubuntu 18.04.1 amd64
GPU: AMD Radeon HD 8670M (Hainan)
CPU: AMD A4-5000
If you need logs, contact me))

**Comment by axeldavy** [comment]
could you show a screenshot ?

**Comment by 18woldemar** [comment]
Screen (Gallium Nine)
[http://priscree.ru/img/ae569896c43e8a.png](url)
Screen (WineD3D)
[http://priscree.ru/img/28db32e000f9a1.png](url)

**Comment by 18woldemar** [comment]
I'm using version 1.0 US HOODLUM. The reason for this bug was found out. It was a SkyGFX mod.
https://gtaforums.com/topic/750681-skygfx-ps2-and-xbox-graphics-for-pc/

**Comment by 18woldemar** [comment]
Trace with mod
https://yadi.sk/d/AVIHEcHT3ZznTb

**Comment by iiv3** [comment]
I can confirm that I do not see the fog when replaying the trace with Gallium Nine, but I do see it with WineD3D.

It means this is not driver specific bug. This should make it easier to fix.

I hope you don't mind if we upload the sample to the Nine ftp and keep it for regression testing.

**Comment by 18woldemar** [comment]
Okay)) Do anything with it.

**Comment by 18woldemar** [comment]
Thank you very much)

**Comment by 18woldemar** [comment]
Another, more detailed trace
https://yadi.sk/d/hRP6S8jY3a2qsi
Do anything with it))

**Comment by axeldavy** [comment]
I looked at the trace, but It's pretty hard to debug because the back buffer format is D3DFMT_A2R10G10B10 and apitrace won't allow me to see the content.

Would it be possible to take a new trace with A8R8G8B8 ? if there is any way to set it.

Second, do the pattern also appear when looking at the tree regions ? It looks like there aren't much items there. To isolate the issue, ideally there would be a few frames displaying the issue with very few items on screen.

To make the trace execute faster (debugging requires relaunching the trace a lot of times ), the trace has to show the problem as fast as possible with as few frames as possible.
It could make a difference to reduce the speed of your graphic card, which you can do with:
sudo chmod ugo+w /sys/class/drm/card0/device/power_dpm_force_performance_level
echo low > /sys/class/drm/card0/device/power_dpm_force_performance_level

then to return to normal speed
echo auto > /sys/class/drm/card0/device/power_dpm_force_performance_level

You may have to replace card0 with card1

**Comment by mirh** [comment]
@aap maybe you know something of that

**Comment by aap** [comment]
Hm, for reference to the others, i'm the author of said mod (skygfx). For the SAMP multiplayer mod i had to tamper with the fog settings a bit but usually they shouldn't be touched unless SAMP is use. Could have something to do with that maybe: https://github.com/aap/skygfx/blob/master/src/main.cpp#L80
Otherwise, try disabling the building pipe hook and see if that changes things. Maybe using a pixel shader somehow breaks fog?

**Comment by axeldavy** [comment]
Given for the same trace the fog appears right with default wine, but not right with nine, the issue is not in the mod, but in nine where there must be a missing corner case unhandled.

**Comment by axeldavy** [comment]
There seems to be only one pixel shader used for all objets affected by shadows, thus I was able to investigate the issue. It seems nine incorrectly compute the depth used for fog effects in some scenarios. I need to make some tests to be sure of the correct formula and not trigger regressions.

**Comment by axeldavy** [comment]
The bug should be corrected by:
https://github.com/iXit/Mesa-3D/commit/633047fab15daa5ad387035d4667b4a21c2ea054

At least the trace seems fine to me.

**Comment by iiv3** [comment]
I applied the patch and tried few older games that are more likely to use fixed functions.
I did not hit any visible regressions.
