### ISSUE TITLE
No guide for new users

### ISSUE THREAD

**Issue by tatsujb** [iXit/Mesa-3D#330]
Why exactly do we have to take a shot in the dark to get gallium nine? 

I don't understand.

anyways this is the sort of stuff that is thrown in our face : https://wiki.ixit.cz/d3d9_install

lots of dead links. 

from my best deduction for me to get a non-distributed gallium-nine onto ubuntu 18.10 (ironically the only   ubuntu distro to support it according to : https://www.omgubuntu.co.uk/2018/10/gallium-nine-ubuntu-18-10 who stay in the trend of not providing a guide or any useful info), is to : 

- download the master branch of wine or wine-staging from github.
- then add these files : https://github.com/sarnex/wine-d3d9-patches to your working directory.
- then according to that readme : "kinda do wateve idunno"

I mean seriously read this garbage please : 

> Use cases:
> a. Vanilla Wine
>   Apply d3d9-helper.patch and then wine-d3d9.patch and then **autoreconf**
> 
> b. Wine Staging
>   Apply all of staging onto vanilla wine, then staging-helper.patch and then wine-d3d9.patch and then **autoreconf**

"not my job" award material right here.

which is it?  get wine? get wine staging? patch wine to wine staging then patch that to gallium?
"Apply all of staging onto vanilla wine, then staging-helper.patch and then wine-d3d9.patch"

this is a fucking joke.

a guide should be clear, have extra info that could be of use and in my mind, if it is in the linux world it's impossible for a guide not to have at least one example terminal command.

**Comment by axeldavy** [comment]
While I agree the website is outdated, hasn't been much updated for years and definitely needs a complete refresh with per-distro instructions, there is no need to have an aggressive attitude.

Remember this is just people taking some time out of their free time to run the project.

These recent months there has been some work to make it easier to install, but there's not much info about that yet visible for end users. When it is finished (hopefully in january or february), we'll definitely update the guidelines.

**Comment by tatsujb** [comment]
sorry it has just been an incredibly frustrating experience, my bad :(

**Comment by axeldavy** [comment]
Gallium nine needs two parts to work, one in mesa and one in wine

Since recently, debian (and thus Ubuntu 18.10), have the mesa part built in their package. Previously you needed ppa for them.you can check it with
find /usr | grep d3dadapter

which should return something of the likes:
/usr/lib32/d3d/d3dadapter9.so.1.0.0
/usr/lib32/d3d/d3dadapter9.so
/usr/lib32/d3d/d3dadapter9.so.1
/usr/lib/d3d/d3dadapter9.so.1.0.0
/usr/lib/d3d/d3dadapter9.so
/usr/lib/d3d/d3dadapter9.so.1
/usr/include/d3dadapter
/usr/include/d3dadapter/drm.h
/usr/include/d3dadapter/d3dadapter9.h
/usr/include/d3dadapter/present.h

As for the the wine part, that's where it is trickier today and are working to make more simple.
playonlinux has among its proposed wine an old wine package running nine, but many games may require more recent wine.
You can use a ppa, like the one of sarnex to get a precompiled wine with nine support.
Unless you are experimented with that, I wouldn't recommend building wine staging with nine support yourself.
What we are working on (you can test https://github.com/dhewg/nine but complete documentation is lacking) will enable to build for any wine installed (no need to recompile wine).

**Comment by axeldavy** [comment]
Since I can't update the old wiki, I made a new one:
https://github.com/iXit/Mesa-3D/wiki

I hope this one is easier to follow.
